// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZuydSDRazor.Data;

#nullable disable

namespace ZuydSDRazor.Migrations
{
    [DbContext(typeof(BontenDbContext))]
    [Migration("20230323150947_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.Property<int>("OnderwerpenOnderwerpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideosVideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OnderwerpenOnderwerpId", "VideosVideoId");

                    b.HasIndex("VideosVideoId");

                    b.ToTable("OnderwerpVideo");
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Onderwerp", b =>
                {
                    b.Property<int>("OnderwerpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .HasColumnType("TEXT");

                    b.HasKey("OnderwerpId");

                    b.ToTable("Onderwerpen");
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Video", b =>
                {
                    b.Property<int?>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.HasOne("ZuydSDRazor.Models.Onderwerp", null)
                        .WithMany()
                        .HasForeignKey("OnderwerpenOnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZuydSDRazor.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
