// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZuydSDRazor.Data;

#nullable disable

namespace ZuydSDRazor.Migrations
{
    [DbContext(typeof(BontenDbContext))]
    partial class BontenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.Property<int>("OnderwerpenOnderwerpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideosVideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OnderwerpenOnderwerpId", "VideosVideoId");

                    b.HasIndex("VideosVideoId");

                    b.ToTable("OnderwerpVideo");
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Koppel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OnderwerpId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OnderwerpId");

                    b.HasIndex("VideoId");

                    b.ToTable("Koppels");
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Onderwerp", b =>
                {
                    b.Property<int>("OnderwerpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OnderwerpId");

                    b.ToTable("Onderwerpen");
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Video", b =>
                {
                    b.Property<int?>("VideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titel")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("OnderwerpVideo", b =>
                {
                    b.HasOne("ZuydSDRazor.Models.Onderwerp", null)
                        .WithMany()
                        .HasForeignKey("OnderwerpenOnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZuydSDRazor.Models.Video", null)
                        .WithMany()
                        .HasForeignKey("VideosVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZuydSDRazor.Models.Koppel", b =>
                {
                    b.HasOne("ZuydSDRazor.Models.Onderwerp", "Onderwerp")
                        .WithMany()
                        .HasForeignKey("OnderwerpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZuydSDRazor.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Onderwerp");

                    b.Navigation("Video");
                });
#pragma warning restore 612, 618
        }
    }
}
